### ISSUE TITLE
KYC-Limit (Betrag in EURO -->  1000 € statt 900 €)

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/payment#195]
**Status:**
Nachdem der Euro gegen den CHF in den letzten Monaten stark nachgegeben hat, 
wurde seitens DFX das Tageslimit ohne KYC-Prozess von 900 € auf 1000 € bereits geändert.

**Problem:**
Jedoch wird offensichtlich auf der Payment-Seite noch das Limit von 900 € angezeigt, 
solange man keinen KYC-Prozess durchlaufen hat.
![KYC-Limit](https://user-images.githubusercontent.com/117222124/199334126-426bcfca-65ff-49a2-be01-0ef3076784c3.png)

**Quelle/Ursprung:**
[https://t.me/DFXswiss/81834](url)
> _Der Service ist bis 1000 CHF bzw. 900 € am Tag  ohne KYC-Prozess nutzbar.  
Aber 1000 CHF sind doch keine 900 € ?_

**Abstellmaßnahme:**
Dieser Sachverhalt sollte bei Gelegenheit zeitnah überarbeitet werden.

**Comment by Kolibri1990** [comment]
Hallo @Wendel-BS ,

ist bereits gefixt.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/66674482/200464152-e64dfa18-f612-4fa5-b2fb-c5a8fb8bd96e.png">
